name: Deploy Flutter Web

on:
  workflow_dispatch:
  push:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: 'Set Flutter 3.19.0'
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: 3.19.0
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter build web --release --base-href /frontend/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
          clean-exclude: pr-preview
