name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
      - name: 'Set Flutter 3.19.0'
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: 3.19.0
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter build web --release --base-href frontend/pr-preview/pr-${{ github.event.number }}/
        if: github.event.action != 'closed'
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
