name: PR Preview Deploy
concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0

      - name: Flutter clean and upgrade
        run: |
          flutter clean
          flutter pub upgrade

      - name: Build web
        run: flutter build web --release --base-href /frontend/

      - name: Generate PR Preview
        run: |
          PR_NUMBER=${{ github.event.number }}
          PREVIEW_DIR="pr-preview/pr-${PR_NUMBER}"
          PREVIEW_URL="https://financrr.github.io/frontend/pr-preview/pr-${PR_NUMBER}/"
          mkdir -p "${PREVIEW_DIR}"
          cp -r build/web/* "${PREVIEW_DIR}/"
          echo "${PREVIEW_URL}" > "${PREVIEW_DIR}/url.txt"

      - name: Print preview link
        run: |
          PR_NUMBER=${{ github.event.number }}
          PREVIEW_URL="https://financrr.github.io/frontend/pr-preview/pr-${PR_NUMBER}/"
          echo "Preview link: ${PREVIEW_URL}"

      - name: Pull changes from remote gh-pages branch
        run: |
          git fetch --prune
          if git show-ref --quiet refs/remotes/origin/gh-pages; then
            git checkout gh-pages
            git pull origin gh-pages
          else
            echo "No gh-pages branch found. Skipping pull."
          fi
          git checkout ${{ github.head_ref }}

      - name: Commit and push PR preview changes
        run: |
          PR_NUMBER=${{ github.event.number }}
          if [ -z "${PR_NUMBER}" ]; then
            echo "Error: PR_NUMBER is empty. Skipping commit and push."
            exit 1
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "pr-preview/pr-${PR_NUMBER}"
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Automated PR Preview for PR ${PR_NUMBER}"
            git push origin HEAD:gh-pages --force
          else
            echo "No changes to commit. Skipping push."
          fi

      - name: Delete old PR previews
        run: |
          if [ -d "pr-preview" ]; then
            git fetch --prune
            for dir in $(ls -d pr-preview/*/); do
              if [[ ! -f "${dir}/url.txt" ]]; then
                PR_NUMBER=$(basename "${dir}")
                git rm -r "${dir}"
                git commit -m "Delete old PR preview for PR ${PR_NUMBER}"
              fi
            done
            git push origin HEAD
          else
            echo "No old PR previews to delete."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pr-preview
