name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Flutter Clean and Upgrade Packages
        run: |
          flutter clean
          flutter pub upgrade

      - name: Build Web
        run: flutter build web --release --base-href /frontend/pr-preview/pr-${{ github.event.number }}/
        if: github.event.action != 'closed'

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/web
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
